import './sass/style.scss'
import Header from './components/Header'
import Footer from './components/Footer'
import PageHeader from './components/PageHeader'
import { fetchMenu } from './utils/fetchData'
import { ContextProvider } from './components/auth/Context'
import Auth from './components/auth/Auth'

export const metadata = {
  title: 'Recipes',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const menuData = await fetchMenu()

  return (
    <html lang="en">
      <body>
        <div className='page'>
          <ContextProvider>
            <Auth>
              <Header menu={menuData}/>
              <div className='content'>
                <PageHeader/>
                {children}
              </div>
              <Footer/>
            </Auth>
          </ContextProvider>
        </div>
      </body>
    </html>
  )
}
